### ISSUE TITLE
Export Charset

### ISSUE THREAD

**Issue by skrosoft** [brookinsconsulting/bccie#12]
Export should be done with UTF8 (no?). Actually export is done with UCS-2 and I have to open the file with another program to convert the file to UTF8 before to be able to open it with Excel.

**Comment by brookinsconsulting** [comment]
Hello @skrosoft 

What OS Platform and version are you using?

What version of Excel are you using?

What version of BC CIE are you using?

What version of eZ Publish are you using?

Please read the following, http://unicode.org/faq/utf_bom.html#utf16-11

Which states, "UCS-2 is obsolete terminology which refers to a Unicode implementation up to Unicode 1.1, before surrogate code points and UTF-16 were added to Version 2.0 of the standard. This term should now be avoided."

Here is the line of code (in master) that encodes the content before it is returned to the browser for download: 

https://github.com/brookinsconsulting/bccie/blob/master/modules/bccie/doexport.php#L151

Currently this encodes content into UTF-16LE (not UCS-2 which is different). This was a recent change contributed by another user claiming that it provided for Excel to open his exports in Excel (on MacOS): https://github.com/brookinsconsulting/bccie/pull/10

We were uncertain about accepting the UTF-16LE change as it seemed to be very platform specific. Just searching in one minute our fears are more or less confirmed:  

http://stackoverflow.com/questions/6588068/which-encoding-opens-csv-files-correctly-with-excel-on-both-mac-and-windows/9070774#9070774

https://www.drupal.org/node/432260

It seems that trying to jump through proprietary platform specific hoops to support double-click opening of csv exports is a madness that may never end.

We're not sure the best answer here as we know users will continue to complain about bccie exports when the real problem is their non-free, incomplete support for standards IE: Excel (on any platform/version). At this point we will begin considering reverting back to plain UTF-8 support and educating users to use free software IE: libre/open office instead.

This was the only answer I would support in the past when -ANYONE- would complain about Excel and csv. http://stackoverflow.com/a/6488070  I would only support this because frankly Excel frankly does not support double-click opening of csv by default or properly; never has and prolly never will. Thus the problem is really not the csv data, utf8, utf16 or bccie. 

Users spit acid and hate in response to my education, they hate that answer (they want double click support) but frankly it is the truth which seems simply can not be avoided. Even when one user shares a fix which works for his program version/os/platform it seems that same fix breaks things for users of another program version/os/platform. I just don't see a common ground in terms of version specific Excel CSV double click to open support.

We would be curious to know your thoughts on the issues at hand.

We are open to suggestions on how to improve the functionality of this extension!

If you wanted to submit a pull request this could help us find a middle of the road solution more quickly.

Cheers,
Brookins Consulting

**Comment by brookinsconsulting** [comment]
Hello @skrosoft 

Sorry for our lack of activity to your very valid issue.

After a lot of thought we have refactored bccie to use a handler system for the export formatting output.
 
https://github.com/brookinsconsulting/bccie/commit/ee1e7add576ea8310c57043dfb369ea5ec8a5ee0

This system can be extended and customized as desired / required.

We also re-introduced pure utf8 as the default cie export encoding.

As a result of these improvements which directly address your issue we are now closing this issue as resolved.

Cheers,
Brookins Consulting
