### ISSUE TITLE
Exporting data from past year

### ISSUE THREAD

**Issue by skrosoft** [brookinsconsulting/bccie#13]
Hi,

I was not able to export CSV data from Dicember 2014. I had to replace this line:

`if ($ci_created < $current_datestamp && $ci_created >= $range )`

by this one

`if (true)`

/classes/parser.php line 308

**Comment by brookinsconsulting** [comment]
Hello @skrosoft 

This issue seems strange to us. Your very vague in your description of a very technical problem.

Your fix seems to avoid the date range support to provided for date based limitations on exported collected information without a real solution to a specific problem.

We have a lot of unanswered questions! Like what is the ci_created value, what is the $range value?

Would you be willing to share (privately, confidentially) a tar.gz compressed sql dump of your database so we can review, debug and test your test case scenario and try to find a more usable solution to the problem in question? This would help me address your request more quickly as I do not have an installation of bccie (on hand) which matches your issue report conditions.

Naturally we won't share your data with anyone and will delete it after completing our review and testing.

Cheers,
Brookins Consulting

**Comment by brookinsconsulting** [comment]
Hello @skrosoft 

Sorry for our lack of activity to your issue.

After some thought we have refactored bccie to use the created date as the 'start export date' by default when doing an export. This date is based on the content so it should always be accurate as the oldest possible start date.
 
https://github.com/brookinsconsulting/bccie/commit/c164a4182757f153cf90f291097aa810f5e98444

As a result of these improvements which directly address your issue we are now closing this issue as invalid but addressed.

Please try the latest version (from github) and see if this solves your concern.

Cheers,
Brookins Consulting
